[project]
name = "langchain79"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.5.6",
    "duckduckgo-search>=8.0.2",
    "groq>=0.26.0",
    "yfinance>=0.2.61",
]
